# Generated by Django 2.1.3 on 2018-11-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181116_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='issue',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='usn',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
