# Generated by Django 2.1.3 on 2018-11-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='facid',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='home.faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_dept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='Not approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='facid',
            field=models.CharField(default='NULL', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(default='NULL', max_length=10, primary_key=True, serialize=False),
        ),
    ]
