# Generated by Django 2.1.3 on 2018-11-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181119_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='facid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.faculty'),
        ),
    ]
