# Generated by Django 2.1.3 on 2018-11-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181119_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(default='NULL', max_length=100)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_dept', models.BooleanField(default=False)),
                ('faculty', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.faculty')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='issue',
        ),
        migrations.AddField(
            model_name='issue',
            name='studentid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
    ]
