# Generated by Django 2.1.3 on 2018-11-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181119_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='branch',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AddField(
            model_name='issue',
            name='facname',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AddField(
            model_name='issue',
            name='name',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AddField(
            model_name='issue',
            name='subject',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='usn',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='facid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.faculty'),
        ),
    ]
