# Generated by Django 2.1.3 on 2018-11-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181120_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='facid',
        ),
    ]
