# Generated by Django 2.1.3 on 2018-11-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_student_facid'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='facid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='facid',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
