# Generated by Django 2.1.3 on 2018-11-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20181120_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='facid',
        ),
        migrations.AddField(
            model_name='student',
            name='facid',
            field=models.ManyToManyField(to='home.faculty'),
        ),
    ]
