# Generated by Django 2.1.3 on 2018-11-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181120_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='facid',
        ),
        migrations.AddField(
            model_name='student',
            name='facid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.faculty'),
        ),
    ]
