# Generated by Django 2.1.3 on 2018-11-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20181120_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='issue',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
