# Generated by Django 2.1.3 on 2018-11-22 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20181120_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='facid',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
