# Generated by Django 2.1.3 on 2018-11-23 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_student_facid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='facid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.faculty'),
        ),
    ]
